package com.qile.entity;
// Generated 2015-12-25 18:49:14 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activity", catalog = "qile")
public class Activity implements java.io.Serializable {

	private Integer id;
	private Integer association;
	private String title;
	private Integer people;
	private String tag;
	private Integer startMonth;
	private Integer endMonth;
	private String content;

	public Activity() {
	}

	public Activity(Integer association, String title, Integer people, String tag, Integer startMonth, Integer endMonth,
			String content) {
		this.association = association;
		this.title = title;
		this.people = people;
		this.tag = tag;
		this.startMonth = startMonth;
		this.endMonth = endMonth;
		this.content = content;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "association")
	public Integer getAssociation() {
		return this.association;
	}

	public void setAssociation(Integer association) {
		this.association = association;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "people")
	public Integer getPeople() {
		return this.people;
	}

	public void setPeople(Integer people) {
		this.people = people;
	}

	@Column(name = "tag", length = 45)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "start_month")
	public Integer getStartMonth() {
		return this.startMonth;
	}

	public void setStartMonth(Integer startMonth) {
		this.startMonth = startMonth;
	}

	@Column(name = "end_month")
	public Integer getEndMonth() {
		return this.endMonth;
	}

	public void setEndMonth(Integer endMonth) {
		this.endMonth = endMonth;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
