package com.qile.entity;
// Generated 2015-12-24 20:56:24 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name = "coupon", catalog = "qile")
public class Coupon implements java.io.Serializable {

	private Integer id;
	private String title;
	private String description;
	private Integer price;
	private Date startday;
	private Date endday;

	public Coupon() {
	}

	public Coupon(String title, String description, Integer price, Date startday, Date endday) {
		this.title = title;
		this.description = description;
		this.price = price;
		this.startday = startday;
		this.endday = endday;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startday", length = 19)
	public Date getStartday() {
		return this.startday;
	}

	public void setStartday(Date startday) {
		this.startday = startday;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endday", length = 19)
	public Date getEndday() {
		return this.endday;
	}

	public void setEndday(Date endday) {
		this.endday = endday;
	}

}
